### ISSUE TITLE
システムの画像とデザイン

### ISSUE THREAD

**Issue by petamoriken** [petamoriken/wagamama#1]
現状
https://moriken.kimamass.com/wagamama/system.html

<img width="1123" alt="2017-09-24 16 35 39" src="https://user-images.githubusercontent.com/2622837/30780478-779447e0-a146-11e7-8412-7c550eb3d75c.png">

**Comment by petamoriken** [comment]
決めないといけないこと

- [x] 貰ったサムネの画像がデザインに比べて横幅が大きい（小さくする？）

  <img width="892" alt="2017-09-24 16 38 12" src="https://user-images.githubusercontent.com/2622837/30780491-f8dbaa5a-a146-11e7-91db-4108e4116921.png">

  ちなみに横幅が 200px だと以下の通り。ただこれだと小さすぎて画面がわからなさそう
  → クリックした時にモーダルを出すようにする手もある（寮の[このページ](http://www.design.kyushu-u.ac.jp/~ijiriryo/facilities)みたいに画像をクリックしたら全画面表示されるやつ。めんどい）

  <img width="727" alt="2017-09-24 16 41 16" src="https://user-images.githubusercontent.com/2622837/30780520-82d1da5e-a147-11e7-876e-38c390fe2d43.png">

- [x] バトルの画像のデザインが横に広いがどうするか（そもそもサムネを貰えてない）
- [x] スマートフォンで見た時にバトル、ドラマのページのサムネに重なるテキストをどうするか（表示させるなら何処に？）

欲しい素材

- [ ] フィールド、バトル、ドラマのボタンの下のボーダーを切り取ったやつ

  ![button_field1](https://user-images.githubusercontent.com/2622837/30780553-6ad6cd00-a148-11e7-9bab-bdfc8e5454b3.png)

  ↓

  ![button_field_trim](https://user-images.githubusercontent.com/2622837/30781220-f5a5e8b4-a155-11e7-8219-4952e0f5fa7b.png)

**Comment by chicchiisk** [comment]
- クリックしたときモーダル出す方式にしてほしいです
- サムネの横幅は200pxで行きましょう
- フィールド、バトル、ドラマのいずれのサムネも200px統一で、でかい画像は別で用意します
- サムネとそれに重なるテキスト問題。テキストを含んだサムネ画像を用意すれば何とかなりませんか？

**Comment by petamoriken** [comment]
デザイン案

* 全体

  - [ ] サムネは width 300px 統一のほうがいい？

* フィールド

  ![system_field](https://user-images.githubusercontent.com/2622837/30982331-08426ab4-a4c2-11e7-8c52-f8db78228312.png)

* バトル

  - [ ] モーダルにするのであれば、画像は重ねないほうがよさそう
  - [ ] 横長の画像をスマートフォンでどうするか

  ![system_battle](https://user-images.githubusercontent.com/2622837/30982337-0a493cc0-a4c2-11e7-9097-f904e59e961f.png)

* ドラマシーン

  ![system_drama](https://user-images.githubusercontent.com/2622837/30982340-0ba021ec-a4c2-11e7-9f1c-350f20648baf.png)

**Comment by chicchiisk** [comment]
・モーダルですが、重ねたままで、重なっている部分は上の画像優先でクリックできるようにできませんか？
・スマホ表示の場合は、縦並びになるように（重ねないように）表示を変えることはできますか？

**Comment by petamoriken** [comment]
@chicchi0531 

> モーダルですが、重ねたままで、重なっている部分は上の画像優先でクリックできるようにできませんか？

技術的には可能なんだけど、クリック可能な要素を重ねるのは全然見ないし、UX 上まずいと思う。

> スマホ表示の場合は、縦並びになるように（重ねないように）表示を変えることはできますか？

自分が危惧してるのは端末の横幅に合わせて画像を拡大縮小して並べることになるんだけど、横長の画像はそうでない画像に比べて表示が小さくなってしまうっていうところやね。
まあ、表示する時に工夫すれば上手くいく気がしてきたから大丈夫っす。:joy:

**Comment by chicchiisk** [comment]
モーダルの部分、重ならないようにずらすと空白が目立つので、あまりずらしたくはないですね。
重なっている部分もそこまで大きいわけではないので、
技術的に可能ならば重ねたまま実装してもらえませんか？

**Comment by petamoriken** [comment]
@chicchi0531 
空白が目立つのが嫌なのであれば、要素を4つにして敷き詰めるのは厳しい？
他のページはきれいに並んでいてここだけ強調させている意味でのこの並び方なのだと思うけど、ちょっと個人的にどうかな:thinking:と感じてる（クリックされうるので）。

**Comment by chicchiisk** [comment]
実装したものを見せてください。
自分が触ってみて違和感を感じるようでしたら
4つにしたりなどを検討したいと思います。

**Comment by petamoriken** [comment]
* `text/system_drama_sub02.png` の右が少し切れてる
* `accessory/border.png` を連続可能にする
* `button/{battle, field, drama}.png` の下に線が入ってしまっている

**Comment by petamoriken** [comment]
* button/{battle, field, drama}.png の下の左右に線を入れる

**Comment by petamoriken** [comment]
complete
